// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABMgAzowbSHeK_Z015jNP2qZDm7F6mb4Q',
    appId: '1:139437726878:android:22f30413f1cdf92f03af8f',
    messagingSenderId: '139437726878',
    projectId: 'mybait-95d70',
    storageBucket: 'mybait-95d70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB96Jw3u7huBjb8NBDQsktLAIxm7nxgymc',
    appId: '1:139437726878:ios:d45fd16c854a622503af8f',
    messagingSenderId: '139437726878',
    projectId: 'mybait-95d70',
    storageBucket: 'mybait-95d70.appspot.com',
    androidClientId: '139437726878-mm82fh4ujtf67q4nlnvg31fmh1bmq1p3.apps.googleusercontent.com',
    iosClientId: '139437726878-v6h62fatp31iogqgj3e7bcu82fojmrml.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybait',
  );
}
